version: '3.7'
services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: neobistropostgres
      POSTGRES_USER: postgresuser
      POSTGRES_PASSWORD: postgrespassword
      PGDATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
